# Generated by Django 3.2 on 2021-05-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_created=True)),
                ('to', models.EmailField(max_length=254)),
                ('status', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=2000)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField()),
            ],
        ),
    ]
