# Generated by Django 3.2.5 on 2021-07-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_service', '0002_alter_emaillog_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField()),
                ('publication', models.TextField()),
                ('email_sent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='email_service.emaillog')),
            ],
        ),
    ]
