# Generated by Django 3.2.5 on 2021-07-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0002_alter_emaillog_date_time'),
        ('bulk_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='email_sent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='email_service.emaillog'),
        ),
    ]
